branches:
  only:
    - master

configuration:
  - Release

install:
  - build/appveyor/to_install.bat

before_build:
  - build/appveyor/to_before_build.bat

build:
  project: out/msbuild/all.sln

after_build:
  - build/appveyor/to_after_build.bat

