branches:
  only:
    - master

configuration:
  - Release

install:
  - cd build/appveyor/
  - to_install.bat
  - cd ../../

before_build:
  - cd build/appveyor/
  - to_before_build.bat
  - cd ../../

build:
  project: out/msbuild/all.sln

after_build:
  - cd build/appveyor/
  - to_after_build.bat
  - cd ../../

